### ISSUE TITLE
Connecting a steam controller causes FileNotFoundErrors

### ISSUE THREAD

**Issue by git-developer** [C0rn3j/sc-controller#40]
These messages were shown when I connected a steam controller via USB:

```
E evdev         [Errno 2] No such file or directory: '/dev/input/event24'
Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 126, in __init__
    fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event24'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3.10/site-packages/scc/drivers/evdevdrv.py", line 398, in handle_new_device
    dev = evdev.InputDevice(eventnode)
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 128, in __init__
    fd = os.open(dev, os.O_RDONLY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event24'
E evdev         [Errno 2] No such file or directory: '/dev/input/event23'
Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 126, in __init__
    fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event23'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3.10/site-packages/scc/drivers/evdevdrv.py", line 398, in handle_new_device
    dev = evdev.InputDevice(eventnode)
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 128, in __init__
    fd = os.open(dev, os.O_RDONLY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event23'
E evdev         [Errno 2] No such file or directory: '/dev/input/event22'
Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 126, in __init__
    fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event22'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3.10/site-packages/scc/drivers/evdevdrv.py", line 398, in handle_new_device
    dev = evdev.InputDevice(eventnode)
  File "/tmp/.mount_sc-conk3I8dd/usr/lib/python3/dist-packages/evdev/device.py", line 128, in __init__
    fd = os.open(dev, os.O_RDONLY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event22'
```

Environment: `sc-controller-v0.4.9.4-jammy-x86_64.AppImage`

I went to `/dev/input/` after seeing these message. The OS is right: both files `/dev/input/event23` and `/dev/input/event24` do not exist. The last devices are:
```
/dev/input/event19:     SCController Keyboard
/dev/input/event20:     SCController Mouse
/dev/input/event21:     Microsoft X-Box 360 pad
```

**Comment by C0rn3j** [comment]
iirc it's some event123_whatever files which we shouldn't be matching but there's a dumb wildcard instead of a regex.

**Comment by C0rn3j** [comment]
The relevant function should be here if you want to take a stab at it

```python
	@staticmethod
	def get_event_node(syspath: str):
		filename = syspath.split("/")[-1]
		if not filename.startswith("event"):
			return None
		print(syspath)
		return f"/dev/input/{filename}"
```

Just add the print in `drivers/evdevdrv.py` and run `./run.sh daemon`

It's hard to repro, managed to do it twice in about 15 minutes with a PS4 controller over USB (might have accidentally connected it over BT) as the errors were triggered by UHID paths.

We could simply do a check if `/dev/input/{filename}` exists before returning it at that point, but it'd be nicer to be able to reliably repro and see what's happening better.

**Comment by git-developer** [comment]
Thanks for looking. I'm currently quit busy, I'll have a look and report back when I find the time.

**Comment by C0rn3j** [comment]
There are two issues.

One is what you reported - I am guessing it is triggered by scc daemon starting and killing the old daemon(? presumably since run.sh sends a kill) - and am guessing the emulated device is then disappeared while it's being checked so we have a race condition.

And one is what I reported, which is SCC finding things like `/sys/devices/pci0000:00/wakeup/wakeup70/event_count`.

```
Traceback (most recent call last):
  File "/home/c0rn3j/Projects/sc-controller/.env/lib/python3.14/site-packages/evdev/device.py", line 125, in __init__                                                                                   
    fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)                                                                                                                                                        
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event_count'                                                                                                                        
```

I've now fixed the issue *I* ran into via https://github.com/C0rn3j/sc-controller/commit/6b081702ab7bea0a3d9b5b8278baba7aec3f6d3b.

**Comment by git-developer** [comment]
Thanks for looking into this. Just to make sure - the commit addresses the second issue, and the race condition is not addressed yet, right?

**Comment by C0rn3j** [comment]
Eyup - I'm thinking we just catch the second one and log it instead of
throwing a trace and that's all

**Comment by C0rn3j** [comment]
Should be fixed by https://github.com/C0rn3j/sc-controller/commit/ab5a411e0d3eac4d527053ee0d75dbf712729ff3 (the `errno.ENOENT` case) - we just log it as a warning now.

**Comment by git-developer** [comment]
I can confirm that the FileNotFoundErrors do no longer occur in `sc-controller-0.6.6-noble-x86_64.AppImage`. Thanks!

FYI: When the daemon is terminated, an exception is logged which otherwise seems to have no impact:

```
2026-08-11 09:53:21.027 D SCCDaemon     Controller removed: <SCByCable sc1:2>
Exception ignored in: <module 'threading' from '/tmp/.mount_sc-cond9KYxo/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/tmp/.mount_sc-cond9KYxo/usr/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
  File "/tmp/.mount_sc-cond9KYxo/usr/lib/python3.12/site-packages/scc/sccdaemon.py", line 467, in sigterm
    sys.exit(0)
SystemExit: 0
Traceback (most recent call last):
  File "/tmp/.mount_sc-cond9KYxo/usr/lib/python3.12/weakref.py", line 666, in _exitfunc
    f()
  File "/tmp/.mount_sc-cond9KYxo/usr/lib/python3.12/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_sc-cond9KYxo/usr/lib/python3/dist-packages/usb1/__init__.py", line 2236, in ___close
    assert handle not in finalizer_dict
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
