### ISSUE TITLE
Trying to launch daemon from appimage attempts to find nonexistent Python in cwd

### ISSUE THREAD

**Issue by C0rn3j** [C0rn3j/sc-controller#56]
Stolen from #54, can repro.
```python
player@game-deck ~/Downloads $ ./sc-controller-0.4.9.6-trixie-x86_64.AppImage daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'ds4drv'
W SCCDaemon     Skipping disabled driver 'ds5drv'
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D USB           Registered USB driver for 28de:1205
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fd98482a690>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fd98482a3c0>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fd98482b500>
D SCCDaemon     Created control socket /home/player/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0.0
Exception in thread Thread-2 (_threaded):
Traceback (most recent call last):
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
Exception in thread Thread-3 (_threaded):
Traceback (most recent call last):
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/threading.py", line 1012, in run
    self.run()
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/site-packages/scc/sccdaemon.py", line 1443, in _threaded
    self._target(*self._args, **self._kwargs)
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/site-packages/scc/sccdaemon.py", line 1443, in _threaded
    self.p = subprocess.Popen(self.args, stdin=None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self.p = subprocess.Popen(self.args, stdin=None)
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/subprocess.py", line 1026, in __init__
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
  File "/tmp/.mount_sc-conLqso8q/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/player/Downloads/usr/bin/python'
FileNotFoundError: [Errno 2] No such file or directory: '/home/player/Downloads/usr/bin/python'
```

**Comment by C0rn3j** [comment]
Cannot reproduce anymore.
